name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub # adicionado: step para autenticar no DockerHub
        uses: docker/login-action@v3 # adicionado: action oficial para login no DockerHub
        with: # adicionado: início dos parâmetros de login
          username: ${{ secrets.DOCKERHUB_USERNAME }} # adicionado: usuário do DockerHub via secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }} # adicionado: token do DockerHub via secrets

      - name: Build and push Docker image # adicionado: step para buildar e enviar a imagem
        uses: docker/build-push-action@v5 # adicionado: action oficial para build/push Docker
        with: # adicionado: início dos parâmetros do build/push
          context: . # adicionado: diretório raiz do projeto como contexto do build
          push: true # adicionado: envia a imagem para o DockerHub após o build
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-demo:latest # adicionado: define a tag da imagem no DockerHub

      # - name: Build Docker image
      #   run: docker build -t nginx-demo .
      # (Essas duas linhas acima podem ser removidas, pois o build já é feito no step acima)